---
apiVersion: database.azure.crossplane.io/v1beta1
kind: SQLServerClass
metadata:
  name: standard-mysql
  annotations:
    resourceclass.crossplane.io/is-default-class: "true"
specTemplate:
  forProvider:
    administratorLogin: my-cool-login
    resourceGroupNameRef:
      name: sample-rg
    location: Central US
    sslEnforcement: Disabled
    version: "5.6"
    sku:
      tier: GeneralPurpose
      capacity: 2
      family: Gen5
    storageProfile:
      storageMB: 25600
      backupRetentionDays: 7
      geoRedundantBackup: Disabled
  reclaimPolicy: Delete
  providerRef:
    name: azure-provider
  writeConnectionSecretsToNamespace: crossplane-system
