---
# ResourceClass that defines the blueprint for how a "standard" RDS instance
# should be dynamically provisioned
apiVersion: database.aws.crossplane.io/v1beta1
kind: RDSInstanceClass
metadata:
  name: standard-aws-postgres
  annotations:
    resource: postgresqlinstance.database.crossplane.io/v1alpha1
  labels:
    example: "true"
specTemplate:
  forProvider:
    dbInstanceClass: db.t2.small
    masterUsername: masteruser
    dbSubnetGroupName: RDS_SUBNET_GROUP_NAME
    allocatedStorage: 20
    engine: postgres
    skipFinalSnapshotBeforeDeletion: true
  writeConnectionSecretsToNamespace: crossplane-system
  providerRef:
    name: example
  reclaimPolicy: Delete
