---
## Crossplane Redis Resource class
apiVersion: cache.aws.crossplane.io/v1alpha3
kind: ReplicationGroupClass
metadata:
  name: standard-aws-redis
  annotations:
    resource: rediscluster.cache.crossplane.io/v1alpha1
  labels:
    example: "true"
specTemplate:
  writeConnectionSecretsToNamespace: crossplane-system
  engineVersion: "3.2.4"
  cacheParameterGroupName: default.redis3.2.cluster.on
  cacheNodeType: cache.t2.micro
  automaticFailoverEnabled: true
  numNodeGroups: 1
  replicasPerNodeGroup: 1
  securityGroupIds:
   - REDIS_SECURITY_GROUP
  cacheSubnetGroupName: REDIS_SUBNET_GROUP
  providerRef:
    name: example
  reclaimPolicy: Delete
