---
apiVersion: servicenetworking.gcp.crossplane.io/v1beta2
kind: Connection
metadata:
  name: sample-connection
spec:
  forProvider:
    parent: services/servicenetworking.googleapis.com
    networkRef:
      name: sample-network
    reservedPeeringRangeRefs:
      - name: sample-globaladdress
  reclaimPolicy: Delete
  providerRef:
    name: gcp-provider
