# ResourceClass that defines the blueprint for how a "standard" GCP bucket
# should be dynamically provisioned
apiVersion: storage.gcp.crossplane.io/v1alpha3
kind: BucketClass
metadata:
  name: standard-gcp-bucket
  annotations:
    resource: bucket.storage.crossplane.io/v1alpha1
  labels:
    example: "true"
specTemplate:
  writeConnectionSecretsToNamespace: crossplane-system
  bucketPolicyOnly:
    enabled: true
  labels:
    app: "gitlab-demo"
  location: US
  serviceAccountSecretRef:
    namespace: crossplane-system
    name: demo-gcs-creds
  storageClass: MULTI_REGIONAL
  providerRef:
    name: example
  reclaimPolicy: Delete
