## Crossplane Redis Resource class
apiVersion: cache.gcp.crossplane.io/v1beta1
kind: CloudMemorystoreInstanceClass
metadata:
  name: standard-gcp-redis
  annotations:
    resource: rediscluster.cache.crossplane.io/v1alpha1
  labels:
    example: "true"
specTemplate:
  writeConnectionSecretsToNamespace: crossplane-system
  forProvider:
    region: us-central1
    tier: BASIC
    memorySizeGb: 1
  providerRef:
    name: example
  reclaimPolicy: Delete
