---
apiVersion: network.aws.crossplane.io/v1alpha3
kind: SecurityGroup
metadata:
  name: sample-cluster-sg
spec:
  vpcIdRef:
    name: sample-vpc
  groupName: my-cool-ekscluster-sg
  description: Cluster communication with worker nodes
  reclaimPolicy: Delete
  providerRef:
    name: aws-provider
