---
apiVersion: identity.aws.crossplane.io/v1alpha3
kind: IAMRolePolicyAttachment
metadata:
  name: sample-role-servicepolicy
spec:
  roleNameRef:
    name: sample-eks-cluster-role
  # wellknown policy arn
  policyArn: arn:aws:iam::aws:policy/AmazonEKSServicePolicy
  reclaimPolicy: Delete
  providerRef:
    name: aws-provider
---
apiVersion: identity.aws.crossplane.io/v1alpha3
kind: IAMRolePolicyAttachment
metadata:
  name: sample-role-clusterpolicy
spec:
  roleNameRef:
    name: sample-eks-cluster-role
  # wellknown policy arn
  policyArn: arn:aws:iam::aws:policy/AmazonEKSClusterPolicy
  reclaimPolicy: Delete
  providerRef:
    name: aws-provider
