apiVersion: database.azure.crossplane.io/v1beta1
kind: MySQLServer
metadata:
  labels:
  name: crossplane-wordpress-mysql
spec:
  providerRef:
    name: example
  writeConnectionSecretToRef:
    namespace: crossplane-system
    name: demo-database-connection
  forProvider:
    resourceGroupName: group-westus-1
    location: West US
    sku:
      tier: Basic
      capacity: 1
      family: Gen5
    storageProfile:
      storageMB: 25600
    administratorLogin: myadmin
    version: "5.7"
    sslEnforcement: Disabled
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress
        tier: frontend
    spec:
      containers:
      - name: wordpress
        image: wordpress:4.6.1-apache
        env:
        - name: WORDPRESS_DB_HOST
          valueFrom:
            secretKeyRef:
              name: demo-database-connection
              key: endpoint
        - name: WORDPRESS_DB_USER
          valueFrom:
            secretKeyRef:
              name: demo-database-connection
              key: username
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: demo-database-connection
              key: password
        ports:
        - containerPort: 80
          name: wordpress
---
apiVersion: v1
kind: Service
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  ports:
  - port: 80
  selector:
    app: wordpress
    tier: frontend
  type: LoadBalancer
